#!/usr/bin/env bash
# More conditions with while

n=1
while [ $n -le 20 ]
do
    echo $     case $n in
	4 )
	    echo "bad luck from China" ;;
	9 )
	    echo "bad luck from Japan" ;;
	17 )
	    echo "bad luck from Italy" ;;
    esac
    n=$((n + 1))
done